set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_C_COMPILER "$ENV{X265_CC}")
set(CMAKE_CXX_COMPILER "$ENV{X265_CXX}")
set(CMAKE_AR "$ENV{X265_AR}")
set(CMAKE_RANLIB "$ENV{X265_RANLIB}")
set(CMAKE_STRIP "$ENV{X265_STRIP}")

set(CMAKE_C_FLAGS "$ENV{X265_CFLAGS}")
set(CMAKE_CXX_FLAGS "$ENV{X265_CXXFLAGS}")
set(CMAKE_EXE_LINKER_FLAGS "$ENV{X265_LDFLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS "$ENV{X265_LDFLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS "$ENV{X265_LDFLAGS}")

set(CMAKE_FIND_ROOT_PATH "$ENV{X265_PREFIX}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
